<?
$html = "
        Databases = [
        {
                salon: 'ROHNERT PARK SALON - LINH T',
                latlng: {
                    lat: '38.3467',
                    lng: '-122.706'},
                address: '70 RALEYS TOWN CENTER',
                homepage: '',
                image_url: '',
                phone_number: '707-584-5018',
                email: '',
                country: '225',
                city: 'ROHNERT PARK',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=68679&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '579y',
                postalcode: '94928',
                brand: 'Wella'
            },{
                salon: 'BEAUTY CONNECTION PLUS',
                latlng: {
                    lat: '38.4197',
                    lng: '-122.714'},
                address: '1937 SANTA ROSA AVENUE',
                homepage: '',
                image_url: '',
                phone_number: '707-575-7327',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=64713&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '5miles 511y',
                postalcode: '95407',
                brand: 'Wella'
            },{
                salon: 'J.LEONARD-JEFF LEONARD',
                latlng: {
                    lat: '38.4368',
                    lng: '-122.721'},
                address: '10 4TH STREET SUITE #102',
                homepage: '',
                image_url: '',
                phone_number: '707-544-2404',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69866&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '6miles 907y',
                postalcode: '95401',
                brand: 'Wella'
            },{
                salon: 'ELLE LUI',
                latlng: {
                    lat: '38.4391',
                    lng: '-122.72'},
                address: '205 5TH STREET',
                homepage: '',
                image_url: '',
                phone_number: '707-575-1474',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69827&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '6miles 1168y',
                postalcode: '95401',
                brand: 'Wella'
            },{
                salon: 'ELLE LUI - RETAIL ACCT',
                latlng: {
                    lat: '38.4391',
                    lng: '-122.72'},
                address: '205 5TH STREET',
                homepage: '',
                image_url: '',
                phone_number: '707-575-1474',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69275&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '6miles 1168y',
                postalcode: '95401',
                brand: 'Wella'
            },{
                salon: 'MES AMIS SALON - ANDREA',
                latlng: {
                    lat: '38.4403',
                    lng: '-122.714'},
                address: '539 4TH STREET',
                homepage: '',
                image_url: '',
                phone_number: '707-526-8984',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=63311&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '6miles 1239y',
                postalcode: '95401',
                brand: 'Wella'
            },{
                salon: 'MES AMIS',
                latlng: {
                    lat: '38.4403',
                    lng: '-122.714'},
                address: '539 4TH STREET',
                homepage: '',
                image_url: '',
                phone_number: '925-586-3095',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=63308&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '6miles 1239y',
                postalcode: '95401',
                brand: 'Wella'
            },{
                salon: 'L SQUARED SALON',
                latlng: {
                    lat: '38.4415',
                    lng: '-122.712'},
                address: '715 FOURTH STREET',
                homepage: '',
                image_url: '',
                phone_number: '707-526-9456',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=64251&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '6miles 1366y',
                postalcode: '95404',
                brand: 'Wella'
            },{
                salon: 'L SQUARED - ADA',
                latlng: {
                    lat: '38.4415',
                    lng: '-122.712'},
                address: '715 FOURTH ST',
                homepage: '',
                image_url: '',
                phone_number: '707-849-3021',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=65702&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '6miles 1366y',
                postalcode: '95401',
                brand: 'Wella'
            },{
                salon: 'INDIGO HAIR STUDIO',
                latlng: {
                    lat: '38.4418',
                    lng: '-122.714'},
                address: '420 MENDOCINO AVE STE 107',
                homepage: '',
                image_url: '',
                phone_number: '707-568-4200',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=64703&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '6miles 1421y',
                postalcode: '95401',
                brand: 'Wella'
            },{
                salon: 'GINA',
                latlng: {
                    lat: '38.4422',
                    lng: '-122.709'},
                address: '838 FOURTH ST',
                homepage: '',
                image_url: '',
                phone_number: '707-575-3050',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=67176&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '6miles 1430y',
                postalcode: '95404',
                brand: 'Wella'
            },{
                salon: 'BIQUOR N\'\' BIQUOR SALON',
                latlng: {
                    lat: '38.4441',
                    lng: '-122.686'},
                address: '701 VILLAGE COURT',
                homepage: '',
                image_url: '',
                phone_number: '707-578-1072',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69871&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '6miles 1724y',
                postalcode: '95405',
                brand: 'Wella'
            },{
                salon: 'THE COLOR ROOM',
                latlng: {
                    lat: '38.4458',
                    lng: '-122.704'},
                address: '10 4TH ST #223',
                homepage: '',
                image_url: '',
                phone_number: '707-578-8668',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=63799&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '7miles 88y',
                postalcode: '95404',
                brand: 'Wella'
            },{
                salon: 'HIGH SOCIETY SALON',
                latlng: {
                    lat: '38.443',
                    lng: '-122.663'},
                address: '4781 HOEN AVE',
                homepage: '',
                image_url: '',
                phone_number: '707-576-7441',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69874&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '7miles 281y',
                postalcode: '95405',
                brand: 'Wella'
            },{
                salon: 'BLAZING HAIR DESIGN',
                latlng: {
                    lat: '38.4476',
                    lng: '-122.701'},
                address: '1519 FOURTH ST',
                homepage: '',
                image_url: '',
                phone_number: '707-544-1422',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=66020&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '7miles 304y',
                postalcode: '95404',
                brand: 'Wella'
            },{
                salon: 'ALL ABOUT YOU HAIR GALLERY',
                latlng: {
                    lat: '38.4478',
                    lng: '-122.727'},
                address: '1231 CLEVELAND AVE.',
                homepage: '',
                image_url: '',
                phone_number: '707-544-0170',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=68926&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '7miles 565y',
                postalcode: '95401',
                brand: 'Wella'
            },{
                salon: 'MI PIACERE-JILL',
                latlng: {
                    lat: '38.4513',
                    lng: '-122.717'},
                address: '1116 MENDOCINO AVE',
                homepage: '',
                image_url: '',
                phone_number: '707-523-4775',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=64763&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '7miles 840y',
                postalcode: '95401',
                brand: 'Wella'
            },{
                salon: 'MI PIACERE - RHONDA MAZZUCCHI',
                latlng: {
                    lat: '38.4513',
                    lng: '-122.717'},
                address: '1116 MENDOCINO AVE. #10',
                homepage: '',
                image_url: '',
                phone_number: '707-523-4775',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=64044&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '7miles 840y',
                postalcode: '95401',
                brand: 'Wella'
            },{
                salon: 'THE LEADING EDGE SALON',
                latlng: {
                    lat: '38.4505',
                    lng: '-122.734'},
                address: '1360 N. DUTTON AVE. STE.B',
                homepage: '',
                image_url: '',
                phone_number: '707-575-5551',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=68248&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '7miles 1027y',
                postalcode: '95401',
                brand: 'Wella'
            },{
                salon: 'LEADING EDGE',
                latlng: {
                    lat: '38.4505',
                    lng: '-122.734'},
                address: '1360 N DUTTON STE B',
                homepage: '',
                image_url: '',
                phone_number: '707-575-5551',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=67614&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '7miles 1027y',
                postalcode: '95401',
                brand: 'Wella'
            },{
                salon: 'THE LEADING EDGE',
                latlng: {
                    lat: '38.4505',
                    lng: '-122.734'},
                address: '1360 N. DUTTON #B',
                homepage: '',
                image_url: '',
                phone_number: '707-575-5551',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=66999&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '7miles 1027y',
                postalcode: '95401',
                brand: 'Wella'
            },{
                salon: 'ELIOT JAMES SALON',
                latlng: {
                    lat: '38.2365',
                    lng: '-122.639'},
                address: '113 WASHINGTON',
                homepage: '',
                image_url: '',
                phone_number: '707-762-3400',
                email: '',
                country: '225',
                city: 'PETALUMA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69273&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '8miles 252y',
                postalcode: '94952',
                brand: 'Wella'
            },{
                salon: 'ELIOT JAMES',
                latlng: {
                    lat: '38.2354',
                    lng: '-122.642'},
                address: '113 WASHINGTON STREET',
                homepage: '',
                image_url: '',
                phone_number: '707-762-3400',
                email: '',
                country: '225',
                city: 'PETALUMA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=63976&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '8miles 259y',
                postalcode: '94952',
                brand: 'Wella'
            },{
                salon: 'LAUTHR',
                latlng: {
                    lat: '38.2324',
                    lng: '-122.637'},
                address: '226 PETALUMA BLVD',
                homepage: '',
                image_url: '',
                phone_number: '707-721-7064',
                email: '',
                country: '225',
                city: 'PETALUMA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=68162&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '8miles 785y',
                postalcode: '94952',
                brand: 'Wella'
            },{
                salon: 'LAUTHR HAIR SKIN BODY - NANCY P',
                latlng: {
                    lat: '38.2324',
                    lng: '-122.637'},
                address: '226 PETALUMA BLVD',
                homepage: '',
                image_url: '',
                phone_number: '707-781-7064',
                email: '',
                country: '225',
                city: 'PETALUMA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=67239&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '8miles 785y',
                postalcode: '94952',
                brand: 'Wella'
            },{
                salon: 'MOCKINGBIRD HEIGHTS - JENNIFER B',
                latlng: {
                    lat: '38.2355',
                    lng: '-122.626'},
                address: '855 LAKEVILLE ST #106',
                homepage: '',
                image_url: '',
                phone_number: '415-686-1175',
                email: '',
                country: '225',
                city: 'PETALUMA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=67910&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '8miles 915y',
                postalcode: '94952',
                brand: 'Wella'
            },{
                salon: 'BEAUTY STORE & MORE',
                latlng: {
                    lat: '38.2354',
                    lng: '-122.625'},
                address: '933 LAKEVILLE STREET SUITE A10',
                homepage: '',
                image_url: '',
                phone_number: '707-763-3446',
                email: '',
                country: '225',
                city: 'PETALUMA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=67406&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '8miles 972y',
                postalcode: '94952',
                brand: 'Wella'
            },{
                salon: 'A TRES BEAU - LUCY DAVIDSON',
                latlng: {
                    lat: '38.4745',
                    lng: '-122.733'},
                address: '3401 CLEVELAND AVE',
                homepage: '',
                image_url: '',
                phone_number: '707-577-8343',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69038&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '9miles 341y',
                postalcode: '95403',
                brand: 'Wella'
            },{
                salon: 'A TRES BEAU',
                latlng: {
                    lat: '38.4745',
                    lng: '-122.733'},
                address: '3401 CLEVELAND AVE',
                homepage: '',
                image_url: '',
                phone_number: '707-577-8343',
                email: '',
                country: '225',
                city: 'SANTA ROSA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=68517&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '9miles 341y',
                postalcode: '95401',
                brand: 'Wella'
            },{
                salon: 'ROSEANN\'\'S HAIR CUTTING',
                latlng: {
                    lat: '38.3628',
                    lng: '-122.525'},
                address: '13750 B ARNOLD DR.',
                homepage: '',
                image_url: '',
                phone_number: '707-938-3724',
                email: '',
                country: '225',
                city: 'GLEN ELLEN',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69884&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '9miles 1119y',
                postalcode: '95442',
                brand: 'Wella'
            },{
                salon: 'ROSEANN\'\'S HAIRCUTTING-SHARON BURNS',
                latlng: {
                    lat: '38.3628',
                    lng: '-122.525'},
                address: '13750 B ARNOLD DR.',
                homepage: '',
                image_url: '',
                phone_number: '707-938-3724',
                email: '',
                country: '225',
                city: 'GLEN ELLEN',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=64688&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '9miles 1119y',
                postalcode: '95442',
                brand: 'Wella'
            },{
                salon: 'GRAZIA WEST',
                latlng: {
                    lat: '38.2924',
                    lng: '-122.462'},
                address: '248 WEST NAPA STREET STE.B',
                homepage: '',
                image_url: '',
                phone_number: '707-996-6002',
                email: '',
                country: '225',
                city: 'SONOMA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=68928&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '13miles 779y',
                postalcode: '95476',
                brand: 'Wella'
            },{
                salon: 'MADELENE SALON',
                latlng: {
                    lat: '38.2919',
                    lng: '-122.458'},
                address: '27 E. NAPA STREET STE.A',
                homepage: '',
                image_url: '',
                phone_number: '707-935-7400',
                email: '',
                country: '225',
                city: 'SONOMA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=64699&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '13miles 1164y',
                postalcode: '95476',
                brand: 'Wella'
            },{
                salon: 'BROADWAY HAIR COMPANY',
                latlng: {
                    lat: '38.278',
                    lng: '-122.46'},
                address: '1270 BROADWAY',
                homepage: '',
                image_url: '',
                phone_number: '707-935-1871',
                email: '',
                country: '225',
                city: 'SONOMA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=66350&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '13miles 1483y',
                postalcode: '95476',
                brand: 'Wella'
            },{
                salon: 'HALO SALON',
                latlng: {
                    lat: '38.5042',
                    lng: '-122.469'},
                address: '1309 MAIN STREET STE C',
                homepage: '',
                image_url: '',
                phone_number: '707-967-1022',
                email: '',
                country: '225',
                city: 'SAINT HELENA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69902&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '16miles 1332y',
                postalcode: '94574',
                brand: 'Wella'
            },{
                salon: 'ULTIMATE KERR',
                latlng: {
                    lat: '38.578',
                    lng: '-122.578'},
                address: '1007 WASHINGTON ST.',
                homepage: '',
                image_url: '',
                phone_number: '707-942-9230',
                email: '',
                country: '225',
                city: 'CALISTOGA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=64302&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '17miles 881y',
                postalcode: '94515',
                brand: 'Wella'
            },{
                salon: 'NH2',
                latlng: {
                    lat: '38.0899',
                    lng: '-122.555'},
                address: '208 VINTAGE WAY STE K29',
                homepage: '',
                image_url: '',
                phone_number: '415-897-8777',
                email: '',
                country: '225',
                city: 'NOVATO',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=64351&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '19miles 444y',
                postalcode: '94945',
                brand: 'Wella'
            },{
                salon: 'NH2 SALON',
                latlng: {
                    lat: '38.0899',
                    lng: '-122.555'},
                address: '208 VINTAGE WAY STE K29',
                homepage: '',
                image_url: '',
                phone_number: '415-897-8777',
                email: '',
                country: '225',
                city: 'NOVATO',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=63537&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '19miles 444y',
                postalcode: '94945',
                brand: 'Wella'
            },{
                salon: 'NAPA BEAUTY',
                latlng: {
                    lat: '38.3197',
                    lng: '-122.299'},
                address: '3207 JEFFERSON',
                homepage: '',
                image_url: '',
                phone_number: '707-226-6166',
                email: '',
                country: '225',
                city: 'NAPA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69877&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '21miles 1515y',
                postalcode: '94558',
                brand: 'Wella'
            },{
                salon: 'GLAMORAMA',
                latlng: {
                    lat: '38.301',
                    lng: '-122.288'},
                address: '1016 CLINTON STREET',
                homepage: '',
                image_url: '',
                phone_number: '707-258-1366',
                email: '',
                country: '225',
                city: 'NAPA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69882&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '22miles 1039y',
                postalcode: '94559',
                brand: 'Wella'
            },{
                salon: 'GLAMORAMA',
                latlng: {
                    lat: '38.301',
                    lng: '-122.288'},
                address: '1016 CLINTON',
                homepage: '',
                image_url: '',
                phone_number: '#',
                email: '',
                country: '225',
                city: 'NAPA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=64303&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '22miles 1039y',
                postalcode: '94558',
                brand: 'Wella'
            },{
                salon: 'LE MELANGE SALON',
                latlng: {
                    lat: '38.2982',
                    lng: '-122.287'},
                address: '931 COOMBS',
                homepage: '',
                image_url: '',
                phone_number: '707-257-7767',
                email: '',
                country: '225',
                city: 'NAPA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69876&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '22miles 1181y',
                postalcode: '94558',
                brand: 'Wella'
            },{
                salon: 'THE ARRANGEMENT - TERRI BROWN',
                latlng: {
                    lat: '38.2973',
                    lng: '-122.286'},
                address: '821 COOMBS',
                homepage: '',
                image_url: '',
                phone_number: '707-253-2811',
                email: '',
                country: '225',
                city: 'NAPA',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69879&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '22miles 1291y',
                postalcode: '94558',
                brand: 'Wella'
            },{
                salon: 'BEAUTY STORE USA',
                latlng: {
                    lat: '37.98',
                    lng: '-122.565'},
                address: '858 SIR FRANCIS DRAKE',
                homepage: '',
                image_url: '',
                phone_number: '415-453-9568',
                email: '',
                country: '225',
                city: 'SAN ANSELMO',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=66828&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '26miles 352y',
                postalcode: '94960',
                brand: 'Wella'
            },{
                salon: 'SIREN SALON INC',
                latlng: {
                    lat: '37.9763',
                    lng: '-122.563'},
                address: '703 SAN ANSELMO AVE',
                homepage: '',
                image_url: '',
                phone_number: '415-457-4736',
                email: '',
                country: '225',
                city: 'SAN ANSELMO',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=63099&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '26miles 837y',
                postalcode: '94960',
                brand: 'Wella'
            },{
                salon: 'BENVENUTO',
                latlng: {
                    lat: '37.9751',
                    lng: '-122.562'},
                address: '536 SAN ANSELMO',
                homepage: '',
                image_url: '',
                phone_number: '415-454-1347',
                email: '',
                country: '225',
                city: 'SAN ANSELMO',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69274&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '26miles 1004y',
                postalcode: '94960',
                brand: 'Wella'
            },{
                salon: 'SALON DECOTA',
                latlng: {
                    lat: '37.9738',
                    lng: '-122.534'},
                address: '1522 4TH STREET',
                homepage: '',
                image_url: '',
                phone_number: '415-460-6175',
                email: '',
                country: '225',
                city: 'SAN RAFAEL',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=66126&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '27miles 224y',
                postalcode: '94901',
                brand: 'Wella'
            },{
                salon: 'SALON DECOTA - MARYCLARE',
                latlng: {
                    lat: '37.9737',
                    lng: '-122.534'},
                address: '1522 4TH STREET',
                homepage: '',
                image_url: '',
                phone_number: '415-460-6175',
                email: '',
                country: '225',
                city: 'SAN RAFAEL',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=65273&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '27miles 236y',
                postalcode: '94901',
                brand: 'Wella'
            },{
                salon: 'BREWER PHILIPS HAIR DES',
                latlng: {
                    lat: '37.9744',
                    lng: '-122.531'},
                address: '1027 C ST',
                homepage: '',
                image_url: '',
                phone_number: '415-485-1437',
                email: '',
                country: '225',
                city: 'SAN RAFAEL',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=69271&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '27miles 253y',
                postalcode: '94901',
                brand: 'Wella'
            },{
                salon: 'BEAUTY EXPO PLUS',
                latlng: {
                    lat: '37.9731',
                    lng: '-122.527'},
                address: '1009 4TH STREET',
                homepage: '',
                image_url: '',
                phone_number: '415-482-9156',
                email: '',
                country: '225',
                city: 'SAN RAFAEL',
                blogUrl: '/blog-home.aspx?blogid=0',
                salonUrl: '/salon-detail.aspx?id=65963&address=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48V2VsbGFVc2VyTG9jYXRpb24geG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSI%2bPENvdW50cnk%2bVW5pdGVkIFN0YXRlczwvQ291bnRyeT48QWRkcmVzcz45NDkyODwvQWRkcmVzcz48L1dlbGxhVXNlckxvY2F0aW9uPg%3d%3d',
                blog: false,
                distance: '27miles 533y',
                postalcode: '94901',
                brand: 'Wella'
            }];

			DatabaseGoogle = Databases;
			";


			preg_match("/Databases = \[(.*)}\];/s",$html,$matches );
			$json = $matches[1]