DROP DATABASE PROXY; 
CREATE  DATABASE PROXY;
use PROXY;

CREATE TABLE HTTP_PROXIES 
(
	PROXY_HOST varchar(100) NOT NULL,
	ACTIVE TINYINT NOT NULL DEFAULT 1,
	
	CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
	UPDATED DATETIME ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB;
CREATE UNIQUE INDEX idx_PROXY_HOST on HTTP_PROXIES(PROXY_HOST);

CREATE TABLE DOMAIN_INFO
(
	DOMAIN varchar(100) NOT NULL,
	MAX_REQUESTS INT NOT NULL DEFAULT 100,	-- maximum requests in a 24 hour period
	REQUEST_EXPIRE_HOURS INT NOT NULL DEFAULT 24, -- how long before we reset counters for max requests
	
	CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
	UPDATED DATETIME ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB;
CREATE UNIQUE INDEX idx_DOMAIN on DOMAIN_INFO(DOMAIN);

-- keeps track of all requests to a domain trhough proxy
CREATE TABLE PROXY_REQUESTS
(
	PROXY_HOST varchar(100) NOT NULL references HTTP_PROXIES(PROXY_HOST),
	DOMAIN varchar(100) NOT NULL references DOMAIN_INFO(DOMAIN),
	URL varchar(1000),
	CONTENT_LENGTH int,
	IS_BANNED tinyint not null default 0, -- if we see one of these in a 24 hour period, don't do any more requests
	
	CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
	UPDATED DATETIME ON UPDATE CURRENT_TIMESTAMP	
)ENGINE=InnoDB;
